"""add_phonenumber

Revision ID: 337e372c9631
Revises: da5f4856c647
Create Date: 2021-02-21 16:27:32.932142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337e372c9631'
down_revision = 'da5f4856c647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phonenumber', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phonenumber')
    # ### end Alembic commands ###
